apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-course-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: docker.io/library/devops_course:v0.4
        ports:
        - containerPort: 8000
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
